openapi: 3.0.0
info:
  version: '1'
  title: Api-Fiat2Defichain
  description: APIs for DB communication
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/meintest/Api-Fiat2Defichain/1
paths:
  /api/v1/user/:
    get:
      tags:
        - Api-Fiat2Defichain
      summary: Returns a user or creates one if not exists
      responses:
        200:
          description: Ok
  /api/v1/registrations/:
    get:
      tags:
        - Api-Fiat2Defichain
      summary: Get wallet registrations
      responses:
        200:
          description: Ok
  /api/v1/allData/:
    get:
      tags:
        - Api-Fiat2Defichain
      summary: Returns all data from DB
      responses:
        200:
          description: Ok

  /api/v2/addRegistration/:
    post:
      tags:
        - Api-Fiat2Defichain
      summary: Add wallet registrations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Modell'
      responses:
        201:
          description: Created
  /api/v2/transaction/:
    post:
      tags:
        - Api-Fiat2Defichain
      summary: Add/Update Transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Modell'
      responses:
        201:
          description: Created
components:
  schemas:
    Modell:
      type: object
      properties:
        id:
          type: integer
          example: 123456
        name:
          type: string
          maxLength: 20
        werk:
          type: integer